version: '3.7'
services:

  mongodb:
    image: mongo:5.0.14
    container_name: stribog-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=stribog
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27019:27017

  postgres:    
    image: postgres:15
    container_name: stribog-postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'stribog'
      POSTGRES_PASSWORD: 'stribog'
      POSTGRES_DB: 'stribog'
    ports:
      - 5439:5432

  rabbitmq:    
    image: rabbitmq:3.11.4-management
    container_name: stribog-rabbitmq
    ports:
      - 5679:5672
      - 15679:15672

  redis:
    image: 'bitnami/redis:7.0.7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    container_name: stribog-redis
    ports:
      - "7009:7000"

  app:
    image: app
    container_name: stribog-app
    build: .
    environment:
      PG_URL: 'postgres://stribog:stribog@stribog-postgres:5432/stribog'
      RMQ_URL: 'amqp://guest:guest@stribog-rabbitmq:5672/'
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: stribog-integration
    image: integration
    depends_on:
      - app

volumes:
  pg-data:
