version: '1.3'
services:

  mongodb:
    image: mongo:5.0.14
    container_name: gotasks-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=gotasks
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27018:27017

  postgres:    
    image: postgres:15
    container_name: gotasks-postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'gotasks'
    ports:
      - 5432:5432

  rabbitmq:    
    image: rabbitmq:3.11.4-management
    container_name: gotasks-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: 'bitnami/redis:7.0.7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    container_name: gotasks-redis
    ports:
      - "7000:7000"

  app:
    #image: debian:bookworm
    image: app
    container_name: gotasks-app
    build: .
    environment:
      PG_URL: 'postgres://user:postgres@gotasks-postgres:5432/gotasks'
      RMQ_URL: 'amqp://guest:guest@gotasks-rabbitmq:5672/'
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: gotasks-integration
    image: integration
    depends_on:
      - app

volumes:
  pg-data:
